
import React from 'react';

export const TRANSLATIONS = {
  fr: {
    title: "FILTER",
    subtitle: "STUDIO",
    login: "Connexion",
    logout: "Déconnexion",
    tools: "Outils",
    import: "Modèles",
    scratch: "De Zéro",
    event: "Événement",
    upload: "Importer Image",
    uploadHint: "Glissez vos logos ici",
    text: "Ajouter Texte",
    textPlaceholder: "Ex: Mariage de Mariem",
    summary: "Résumé du Devis",
    order: "Passer la Commande",
    orderNow: "Commander",
    secure: "Paiement sécurisé par cryptage",
    aiSuggest: "Suggestions IA",
    wedding: "Mariage",
    birthday: "Anniversaire",
    baby: "Naissance",
    custom: "Personnalisé",
    checkoutTitle: "Finaliser votre commande",
    processing: "Validation du transfert...",
    paymentSuccess: "Succès ! Votre filtre sera prêt dans 24h après vérification du transfert.",
    saveDraft: "Publier dans la Boutique",
    updateDraft: "Mettre à jour le Filtre",
    reset: "Réinitialiser",
    currency: "MRU",
    nbTexts: "Textes ajoutés",
    nbImages: "Éléments graphiques",
    adminPrice: "Prix de vente (MRU)",
    shareText: "Découvrez mon nouveau design de filtre sur FilterStudio Pro !",
    download: "Télécharger Aperçu",
    myDrafts: "Mes Projets Sauvegardés",
    noDrafts: "Aucun modèle disponible pour le moment.",
    loadDraft: "MODIFIER",
    deleteDraft: "SUPPRIMER",
    viewGallery: "EXPLORER LES FILTRES",
    backToEditor: "CRÉER MON FILTRE",
    galleryTitle: "Catalogue de Filtres",
    gallerySubtitle: "Choisissez un design d'exception pour votre événement.",
    myLibrary: "MES DESIGNS"
  },
  ar: {
    title: "فلتر",
    subtitle: "ستوديو",
    login: "دخول",
    logout: "خروج",
    tools: "أدوات",
    import: "نماذج",
    scratch: "من الصفر",
    event: "المناسبة",
    upload: "إدراج صورة",
    uploadHint: "اسحب الشعارات هنا",
    text: "إضافة نص",
    textPlaceholder: "مثال: زواج مريم",
    summary: "ملخص الفاتورة",
    order: "إتمام الطلب",
    orderNow: "طلب الفلتر",
    secure: "دفع آمن وبيانات مشفرة",
    aiSuggest: "اقتراحات الذكاء الاصطناعي",
    wedding: "زواج",
    birthday: "عيد ميلاد",
    baby: "ولادة",
    custom: "مخصص",
    checkoutTitle: "إتمام الطلب",
    processing: "جاري التحقق من الدفع...",
    paymentSuccess: "تم بنجاح! سيصلك الفلتر خلال 24 ساعة بعد تأكيد التحويل.",
    saveDraft: "نشر في المتجر",
    updateDraft: "تحديث التصميم",
    reset: "إعادة ضبط",
    currency: "أوقية",
    nbTexts: "النصوص المضافة",
    nbImages: "عناصر جرافيك",
    adminPrice: "سعر البيع (أوقية)",
    shareText: "شاهد تصميم الفلتر الجديد الخاص بي على FilterStudio Pro!",
    download: "تحميل العرض",
    myDrafts: "مشاريعي المحفوظة",
    noDrafts: "لا توجد نماذج حالياً.",
    loadDraft: "تعديل",
    deleteDraft: "حذف",
    viewGallery: "تصفح الفلاتر",
    backToEditor: "صمم فلترك",
    galleryTitle: "كتالوج الفلاتر المميزة",
    gallerySubtitle: "اختر تصميماً استثنائياً لمناسبتك الخاصة.",
    myLibrary: "تصاميمي"
  }
};

export const PHONE_BG_IMAGE = 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80';
export const PRICE_PREMIUM_DEFAULT = 1200;
